#Q1.What is the total Revenue generated by the coffee shop?
SELECT sum(money) AS Total_Revenue 
FROM index_2;

#Q2.Which cofee is sold most?
SELECT coffee_name,count(*) AS Total_orders
FROM index_2
GROUP BY coffee_name
ORDER BY Total_orders DESC
LIMIT 1;

#Q3.Which are the top 3 coffees that generate the highest revenue?
SELECT coffee_name,SUM(money) As Total_Revenue 
from index_2 
GROUP BY coffee_name
ORDER BY Total_Revenue DESC
LIMIT 3;

#Q4.What is the camparison between Cash vs card payments?
SELECT cash_type,count(*) AS Transactions 
FROM index_2
GROUP BY cash_type;

#Q5.What is the total Revenue by generated by each payment type?
SELECT cash_type,SUM(money) AS Total_Revenue
FROM index_2
GROUP BY cash_type;

#Q6.What are the peak hours when the coffee shop recieve the highest number of records?
SELECT HOUR(datetime) AS Hour,
COUNT(*) AS Total_Orders
FROM index_2
GROUP BY HOUR(datetime)
ORDER BY Total_Orders DESC;

#Q7.What is the Average customer Spending per transactions?
SELECT avg(money) AS Avg_Spending
FROM index_2;

#Q8.Which transactions have sales greater than 20?
SELECT coffee_name,money
FROM index_2
WHERE money > 20;

#Q9.What are the different types of coffee available in the dataset?
SELECT DISTINCT coffee_name
FROM index_2;

#Q10.How can we assign a Row number to each transaction?
SELECT coffee_name,money,cash_type,datetime,
ROW_NUMBER() over(ORDER BY datetime) AS Row_Num
FROM index_2;




